#!/bin/bash
alias gpl="git pull"
alias gs="git status"
alias gpsh="git push"
alias grbs="git rebase"
alias gc="git commit"
alias gcm="git commit -m"
alias gca="git commit --amend"
alias dps="docker ps"
alias gg="git log --oneline --graph"
alias d="docker"
alias dc="docker-compose"
alias dcls="docker-compose ls"
alias dc="docker-compose"
alias wdps="watch docker ps"
alias wdcls="watch docker-compose ls"
alias lp="sudo netstat -tulpn"
alias 0chain="~/0chain/0chain.sh"